import myPhoto from "../../assets/aboutMePhoto.png";
import Footer from "../../components/shared/Footer/Footer";
import Header from "../../components/shared/Header/Header";
import { useScrollRestoration } from "../../hooks/useScrollRestoration";
import styles from "./About.module.css";

const About = () => {
  useScrollRestoration();

  return (
    <div className={styles.aboutPage}>
      <Header />
      <main className={styles.mainContent}>
        <section className={styles.hero}>
          <h1>Your Personal Vocabulary Coach</h1>
          <p className={styles.subtitle}>
            Eat Word is an AI-powered platform to help you master the words that
            matter most in your life.
          </p>
        </section>

        <section className={styles.whatIsEatWord}>
          <h2>What is Eat Word?</h2>
          <p>
            Unlike traditional apps cluttered with generic lists, Eat Word
            starts as a blank canvas. You choose words from your world: a
            technical term from a work document, a phrase from a novel, or a
            concept you struggled with in a meeting. The AI then generates
            everything you need to learn it for good.
          </p>
          <div className={styles.featuresGrid}>
            <div className={styles.feature}>
              <h3>Your Words, Your Rules</h3>
              <p>
                Add any word or phrase you encounter. The app adapts to your
                goals, whether for exams, work, or personal growth.
              </p>
            </div>
            <div className={styles.feature}>
              <h3>AI-Powered Learning</h3>
              <p>
                Get simple definitions, real-life examples, pronunciations, and
                synonyms instantly generated by AI.
              </p>
            </div>
            <div className={styles.feature}>
              <h3>Science-Backed Methods</h3>
              <p>
                We use Active Recall, Spaced Repetition, and Contextual
                Learning to make sure your new vocabulary sticks.
              </p>
            </div>
          </div>
        </section>

        <section className={styles.whyEatWord}>
          <h2>Why I Built Eat Word</h2>
          <div className={styles.story}>
            <div className={styles.storySection}>
              <h3>The Struggle</h3>
              <p>
                As a non-native English speaker, I often found myself knowing
                textbook definitions but struggling to use words confidently in
                real conversations. I would memorize lists of words only to
                forget them a week later. It was frustrating and inefficient.
              </p>
            </div>
            <div className={styles.storySection}>
              <h3>The Discovery</h3>
              <p>
                I researched learning science and discovered three powerful
                techniques: <strong>Active Recall</strong> (testing yourself),{" "}
                <strong>Spaced Repetition</strong> (reviewing at strategic
                intervals), and <strong>Contextual Learning</strong> (using
                words in real-world examples). These methods changed everything.
              </p>
            </div>
            <div className={styles.storySection}>
              <h3>The Solution</h3>
              <p>
                I built Eat Word to automate this process. It started as a
                personal tool but grew into a platform that helps thousands learn
                the words they actually need. It’s the vocabulary coach I always
                wished I had.
              </p>
            </div>
          </div>
        </section>

        <section className={styles.aboutMe}>
          <h2>About the Developer</h2>
          <div className={styles.aboutMeContent}>
            <div className={styles.aboutMeImage}>
              <img src={myPhoto} alt="Naime, the creator of Eat Word" />
            </div>
            <div className={styles.aboutMeBio}>
              <h3>Naime</h3>
              <p>
                I&#39;m a software developer from Bangladesh who loves building
                tools that solve real problems. Eat Word was born from my own
                struggle with learning English vocabulary, and it brings me joy
                to see it help others on their learning journey.
              </p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default About;